### ISSUE TITLE
Add screenshot to Xunit report

### ISSUE THREAD

**Issue by DITLPANW** [ranorex/Ranorex-To-XUnit#1]
Hi All,
I still work with this current version and the format of this logs work well but the screenshot attached are missing. 
There is option to add the attached to the xunit report? 
Thanks.

**Comment by ranorex** [comment]
Hello,

With Ranorex 7.0 a new feature was introduced allowing optional jUnit reports:
https://www.ranorex.com/help/latest/lesson-8-reporting#Lesson8-Reporting-JUnit-compatiblereports

Thus, this xsl transformation will no longer be developed further by Ranorex. The transformation as it is does not support screenshots or attachments.

Thank you for valuable input.
